logo: "/assets/images/sri-lanka_flag.png"
title: You open - Sri-Lanka
email: komradaxon@gmail.com
description: Information about Sri-Lanka for ru-speak tourists and expats.
domain: sri-lanka.you-open.com
url: "https://sri-lanka.you-open.com/"
github_username: ComradeAx0n

remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3

show_downloads: false
google_analytics: G-QH27QWY0H1

aux_links:
  "You open - Sri-Lanka на GitHub":
    - "//github.com/ComradeAx0n/you-open-sri-lanka"

back_to_top: true
back_to_top_text: "Вернуться наверх"

gh_edit_link: true
gh_edit_link_text: "Отредактировать страницу на GitHub"
gh_edit_repository: "https://github.com/ComradeAx0n/you-open-sri-lanka"
gh_edit_branch: "master"
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree"
